databases:
  - name: quote_editor_db
    databaseName: quote_editor_db
    user: quote_editor_db_user
    plan: free

services:
  - type: redis
    name: quote-editor-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: [] # Only allow internal connections

  - type: web
    name: quote-editor-web
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quote_editor_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: quote-editor-redis
          property: connectionString
          type: redis
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default